### ISSUE TITLE
`upload-artifact` v3 is deprecated

### ISSUE THREAD

**Issue by marekdedic** [relative-ci/agent-upload-artifact-action#2]
Hi,
this action still uses the v3 of `actions/upload-artifact`, which is deprecated. Could you please update it to v4?

**Comment by vio** [comment]
Thank you for creating the issue, @marekdedic! We are planning a maintenance release for the agents and will make sure this is included as well.

**Comment by vio** [comment]
[v2.0.0 released](https://github.com/relative-ci/agent-upload-artifact-action/releases/tag/v2.0.0) with `actions/upload-artifact@v4`.

**Comment by marekdedic** [comment]
Great, thanks!
